// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjTLqgNAI7NGJHms8SCfYu9Vtgbm_O-lU',
    appId: '1:928071833947:web:a86abeeed177bde137227e',
    messagingSenderId: '928071833947',
    projectId: 'happypawsv2',
    authDomain: 'happypawsv2.firebaseapp.com',
    storageBucket: 'happypawsv2.appspot.com',
    measurementId: 'G-WDC1YR8NX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ujg_Z8qCXj_J03WNmrXPVvvYMc7xppc',
    appId: '1:928071833947:android:8763d7134ea903e437227e',
    messagingSenderId: '928071833947',
    projectId: 'happypawsv2',
    storageBucket: 'happypawsv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJkStUa1K8J_CXNYXy18VFJcbrdUFOZ84',
    appId: '1:928071833947:ios:872231c7d302664637227e',
    messagingSenderId: '928071833947',
    projectId: 'happypawsv2',
    storageBucket: 'happypawsv2.appspot.com',
    iosClientId: '928071833947-umve8s8glogc72s9fiduha09js9liq8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyPawsV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJkStUa1K8J_CXNYXy18VFJcbrdUFOZ84',
    appId: '1:928071833947:ios:b67bd2bec0fe171b37227e',
    messagingSenderId: '928071833947',
    projectId: 'happypawsv2',
    storageBucket: 'happypawsv2.appspot.com',
    iosClientId: '928071833947-b654p24aj32d279tur7lshf9jkid9fra.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyPawsV2.RunnerTests',
  );
}
